### ISSUE TITLE
Memory Limit Reached for ZF1 Project

### ISSUE THREAD

**Issue by the-poops** [zend-server-extensions/Z-Ray-ZF1#5]
Note: Using the newest version of ZF1/zray.php (downloaded today)

When trying to view a page having Z-Ray enabled, I get a WSOD page.  I checked the logs:

$ tail -f /usr/local/zend/var/log/php.log 
Stack trace:
#0 /usr/local/zend/apache2/htdocs/my-project/library/Zend/Application/Bootstrap/Bootstrap.php(97): ArrayObject->serialize()
#1 /usr/local/zend/apache2/htdocs/my-project/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /usr/local/zend/apache2/htdocs/my-project/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /usr/local/zend/apache2/htdocs/my-project/index.php(34): Zend_Application->run()
#4 {main}
  thrown in /usr/local/zend/apache2/htdocs/my-project/library/Zend/Controller/Front.php on line 0
[08-Jun-2015 18:12:51 America/Los_Angeles] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /usr/local/zend/var/zray/extensions/ZF1/zray.php on line 238
[08-Jun-2015 18:13:09 America/Los_Angeles] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 130968 bytes) in /usr/local/zend/var/zray/extensions/ZF1/zray.php on line 271
[08-Jun-2015 18:19:42 America/Los_Angeles] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /usr/local/zend/var/zray/extensions/ZF1/zray.php on line 252
^C

Note: using Zend Server 8.0.2.  I upgraded zray.php because the version that came with Zend Server 8.0.2 was causing a weird error (shown below):

Uncaught exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in /usr/local/zend/apache2/htdocs/my-project/library/Zend/Controller/Front.php:0 Stack trace: #0 /usr/local/zend/apache2/htdocs/my-project/library/Zend/Application/Bootstrap/Bootstrap.php(97): ArrayObject->serialize() #1 /usr/local/zend/apache2/htdocs/my-project/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch() #2 /usr/local/zend/apache2/htdocs/my-project/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run() #3 /usr/local/zend/apache2/htdocs/my-project/index.php(33): Zend_Application->run() #4 {main} thrown

**Comment by amitdar** [comment]
Thank you for your feedback, the issue already fixed and will be available in the next release (really soon...)
